/*
 *  MIT License
 *
 *  Copyright (c) 2021 Gael Rial Costas
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

package io.github.gaeqs.nes4jams.cpu.instruction

import io.github.gaeqs.nes4jams.cpu.NESCPU
import kotlin.reflect.KFunction
import io.github.gaeqs.nes4jams.cpu.instruction.NESAddressingMode as AddressingMode

data class NESAssembledInstruction(
    val mnemonic: String,
    val operation: KFunction<Boolean>,
    val addressingMode: AddressingMode,
    val cycles: UByte,
    val dummyRead: DummyRead = DummyRead.NEVER
) {
    companion object {

        val INSTRUCTIONS = arrayOf(
            /*00*/    NESAssembledInstruction("BRK", NESCPU::brk, AddressingMode.IMMEDIATE, 7u, DummyRead.ALWAYS),
            /*01*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.INDIRECT_X, 6u),
            /*02*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*03*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            /*04*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE, 3u),
            /*05*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ZERO_PAGE, 3u),
            /*06*/    NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ZERO_PAGE, 5u),
            /*07*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            /*08*/    NESAssembledInstruction("PHP", NESCPU::php, AddressingMode.IMPLIED, 3u, DummyRead.ALWAYS),
            /*09*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.IMMEDIATE, 2u),
            /*0a*/    NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.IMPLIED, 2u),
            /*0b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*0c*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE, 4u),
            /*0d*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ABSOLUTE, 4u),
            /*0e*/    NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ABSOLUTE, 6u),
            /*0f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*10*/    NESAssembledInstruction("BPL", NESCPU::bpl, AddressingMode.RELATIVE, 2u),
            /*11*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*12*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*13*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u, DummyRead.ALWAYS),
            /*14*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE_X, 4u),
            /*15*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ZERO_PAGE_X, 4u),
            /*16*/    NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ZERO_PAGE_X, 6u),
            /*17*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*18*/    NESAssembledInstruction("CLC", NESCPU::clc, AddressingMode.IMPLIED, 2u),
            /*19*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*1a*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*1b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*1c*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*1d*/    NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*1e*/    NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ABSOLUTE_X, 7u, DummyRead.ALWAYS),
            /*1f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*20*/    NESAssembledInstruction("JSR", NESCPU::jsr, AddressingMode.ABSOLUTE, 6u),
            /*21*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.INDIRECT_X, 6u),
            /*22*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*23*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            /*24*/    NESAssembledInstruction("BIT", NESCPU::bit, AddressingMode.ZERO_PAGE, 3u),
            /*25*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ZERO_PAGE, 3u),
            /*26*/    NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ZERO_PAGE, 5u),
            /*27*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            /*28*/    NESAssembledInstruction("PLP", NESCPU::plp, AddressingMode.IMPLIED, 4u, DummyRead.ALWAYS),
            /*29*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.IMMEDIATE, 2u),
            /*2a*/    NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.IMPLIED, 2u),
            /*2b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*2c*/    NESAssembledInstruction("BIT", NESCPU::bit, AddressingMode.ABSOLUTE, 4u),
            /*2d*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ABSOLUTE, 4u),
            /*2e*/    NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ABSOLUTE, 6u),
            /*2f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*30*/    NESAssembledInstruction("BMI", NESCPU::bmi, AddressingMode.RELATIVE, 2u),
            /*31*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*32*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*33*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u, DummyRead.ALWAYS),
            /*34*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE_X, 4u),
            /*35*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ZERO_PAGE_X, 4u),
            /*36*/    NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ZERO_PAGE_X, 6u),
            /*37*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*38*/    NESAssembledInstruction("SEC", NESCPU::sec, AddressingMode.IMPLIED, 2u),
            /*39*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*3a*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*3b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*3c*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*3d*/    NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*3e*/    NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ABSOLUTE_X, 7u, DummyRead.ALWAYS),
            /*3f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*40*/    NESAssembledInstruction("RTI", NESCPU::rti, AddressingMode.IMPLIED, 6u, DummyRead.ALWAYS),
            /*41*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.INDIRECT_X, 6u),
            /*42*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*43*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            /*44*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE, 3u),
            /*45*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ZERO_PAGE, 3u),
            /*46*/    NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ZERO_PAGE, 5u),
            /*47*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            /*48*/    NESAssembledInstruction("PHA", NESCPU::pha, AddressingMode.IMPLIED, 3u, DummyRead.ALWAYS),
            /*49*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.IMMEDIATE, 2u),
            /*4a*/    NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.IMPLIED, 2u),
            /*4b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*4c*/    NESAssembledInstruction("JMP", NESCPU::jmp, AddressingMode.ABSOLUTE, 3u),
            /*4d*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ABSOLUTE, 4u),
            /*4e*/    NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ABSOLUTE, 6u),
            /*4f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*50*/    NESAssembledInstruction("BVC", NESCPU::bvc, AddressingMode.RELATIVE, 2u),
            /*51*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*52*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*53*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u, DummyRead.ALWAYS),
            /*54*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE_X, 4u),
            /*55*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ZERO_PAGE_X, 4u),
            /*56*/    NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ZERO_PAGE_X, 6u),
            /*57*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*58*/    NESAssembledInstruction("CLI", NESCPU::cli, AddressingMode.IMPLIED, 2u),
            /*59*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*5a*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*5b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*5c*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*5d*/    NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*5e*/    NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ABSOLUTE_X, 7u, DummyRead.ALWAYS),
            /*5f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*60*/    NESAssembledInstruction("RTS", NESCPU::rts, AddressingMode.IMPLIED, 6u, DummyRead.ALWAYS),
            /*61*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.INDIRECT_X, 6u),
            /*62*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*63*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            /*64*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE, 3u),
            /*65*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ZERO_PAGE, 3u),
            /*66*/    NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ZERO_PAGE, 5u),
            /*67*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            /*68*/    NESAssembledInstruction("PLA", NESCPU::pla, AddressingMode.IMPLIED, 4u, DummyRead.ALWAYS),
            /*69*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.IMMEDIATE, 2u),
            /*6a*/    NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.IMPLIED, 2u),
            /*6b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*6c*/    NESAssembledInstruction("JMP", NESCPU::jmp, AddressingMode.INDIRECT, 5u),
            /*6d*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ABSOLUTE, 4u),
            /*6e*/    NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ABSOLUTE, 6u),
            /*6f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*70*/    NESAssembledInstruction("BVS", NESCPU::bvs, AddressingMode.RELATIVE, 2u),
            /*71*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*72*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*73*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u, DummyRead.ALWAYS),
            /*74*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE_X, 4u),
            /*75*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ZERO_PAGE_X, 4u),
            /*76*/    NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ZERO_PAGE_X, 6u),
            /*77*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*78*/    NESAssembledInstruction("SEI", NESCPU::sei, AddressingMode.IMPLIED, 2u),
            /*79*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*7a*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*7b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*7c*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*7d*/    NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*7e*/    NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ABSOLUTE_X, 7u, DummyRead.ALWAYS),
            /*7f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*80*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMMEDIATE, 2u),
            /*81*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.INDIRECT_X, 6u),
            /*82*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMMEDIATE, 2u),
            /*83*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*84*/    NESAssembledInstruction("STY", NESCPU::sty, AddressingMode.ZERO_PAGE, 3u),
            /*85*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ZERO_PAGE, 3u),
            /*86*/    NESAssembledInstruction("STX", NESCPU::stx, AddressingMode.ZERO_PAGE, 3u),
            /*87*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 3u),
            /*88*/    NESAssembledInstruction("DEY", NESCPU::dey, AddressingMode.IMPLIED, 2u),
            /*89*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMMEDIATE, 2u),
            /*8a*/    NESAssembledInstruction("TXA", NESCPU::txa, AddressingMode.IMPLIED, 2u),
            /*8b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*8c*/    NESAssembledInstruction("STY", NESCPU::sty, AddressingMode.ABSOLUTE, 4u),
            /*8d*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ABSOLUTE, 4u),
            /*8e*/    NESAssembledInstruction("STX", NESCPU::stx, AddressingMode.ABSOLUTE, 4u),
            /*8f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            /*90*/    NESAssembledInstruction("BCC", NESCPU::bcc, AddressingMode.RELATIVE, 2u),
            /*91*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.INDIRECT_Y, 6u, DummyRead.ALWAYS),
            /*92*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*93*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u, DummyRead.ALWAYS),
            /*94*/    NESAssembledInstruction("STY", NESCPU::sty, AddressingMode.ZERO_PAGE_X, 4u),
            /*95*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ZERO_PAGE_X, 4u),
            /*96*/    NESAssembledInstruction("STX", NESCPU::stx, AddressingMode.ZERO_PAGE_Y, 4u),
            /*97*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            /*98*/    NESAssembledInstruction("TYA", NESCPU::tya, AddressingMode.IMPLIED, 2u),
            /*99*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ABSOLUTE_Y, 5u, DummyRead.ALWAYS),
            /*9a*/    NESAssembledInstruction("TXS", NESCPU::txs, AddressingMode.IMPLIED, 2u),
            /*9b*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u, DummyRead.ALWAYS),
            /*9c*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 5u, DummyRead.ALWAYS),
            /*9d*/    NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ABSOLUTE_X, 5u, DummyRead.ALWAYS),
            /*9e*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u, DummyRead.ALWAYS),
            /*9f*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u, DummyRead.ALWAYS),
            /*a0*/    NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.IMMEDIATE, 2u),
            /*a1*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.INDIRECT_X, 6u),
            /*a2*/    NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.IMMEDIATE, 2u),
            /*a3*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*a4*/    NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ZERO_PAGE, 3u),
            /*a5*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ZERO_PAGE, 3u),
            /*a6*/    NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ZERO_PAGE, 3u),
            /*a7*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 3u),
            /*a8*/    NESAssembledInstruction("TAY", NESCPU::tay, AddressingMode.IMPLIED, 2u),
            /*a9*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.IMMEDIATE, 2u),
            /*aa*/    NESAssembledInstruction("TAX", NESCPU::tax, AddressingMode.IMPLIED, 2u),
            /*ab*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*ac*/    NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ABSOLUTE, 4u),
            /*ad*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ABSOLUTE, 4u),
            /*ae*/    NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ABSOLUTE, 4u),
            /*af*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            /*b0*/    NESAssembledInstruction("BCS", NESCPU::bcs, AddressingMode.RELATIVE, 2u),
            /*b1*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*b2*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*b3*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u, DummyRead.ON_CARRY),
            /*b4*/    NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ZERO_PAGE_X, 4u),
            /*b5*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ZERO_PAGE_X, 4u),
            /*b6*/    NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ZERO_PAGE_Y, 4u),
            /*b7*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            /*b8*/    NESAssembledInstruction("CLV", NESCPU::clv, AddressingMode.IMPLIED, 2u),
            /*b9*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*ba*/    NESAssembledInstruction("TSX", NESCPU::tsx, AddressingMode.IMPLIED, 2u),
            /*bb*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u, DummyRead.ON_CARRY),
            /*bc*/    NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*bd*/    NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*be*/    NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*bf*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u, DummyRead.ON_CARRY),
            /*c0*/    NESAssembledInstruction("CPY", NESCPU::cpy, AddressingMode.IMMEDIATE, 2u),
            /*c1*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.INDIRECT_X, 6u),
            /*c2*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMMEDIATE, 2u),
            /*c3*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            /*c4*/    NESAssembledInstruction("CPY", NESCPU::cpy, AddressingMode.ZERO_PAGE, 3u),
            /*c5*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ZERO_PAGE, 3u),
            /*c6*/    NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ZERO_PAGE, 5u),
            /*c7*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            /*c8*/    NESAssembledInstruction("INY", NESCPU::iny, AddressingMode.IMPLIED, 2u),
            /*c9*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.IMMEDIATE, 2u),
            /*ca*/    NESAssembledInstruction("DEX", NESCPU::dex, AddressingMode.IMPLIED, 2u),
            /*cb*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*cc*/    NESAssembledInstruction("CPY", NESCPU::cpy, AddressingMode.ABSOLUTE, 4u),
            /*cd*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ABSOLUTE, 4u),
            /*ce*/    NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ABSOLUTE, 6u),
            /*cf*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*d0*/    NESAssembledInstruction("BNE", NESCPU::bne, AddressingMode.RELATIVE, 2u),
            /*d1*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*d2*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*d3*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u, DummyRead.ALWAYS),
            /*d4*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE_X, 4u),
            /*d5*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ZERO_PAGE_X, 4u),
            /*d6*/    NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ZERO_PAGE_X, 6u),
            /*d7*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*d8*/    NESAssembledInstruction("CLD", NESCPU::cld, AddressingMode.IMPLIED, 2u),
            /*d9*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*da*/    NESAssembledInstruction("NOP", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*db*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*dc*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*dd*/    NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*de*/    NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ABSOLUTE_X, 7u, DummyRead.ALWAYS),
            /*df*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*e0*/    NESAssembledInstruction("CPX", NESCPU::cpx, AddressingMode.IMMEDIATE, 2u),
            /*e1*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.INDIRECT_X, 6u),
            /*e2*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMMEDIATE, 2u),
            /*e3*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            /*e4*/    NESAssembledInstruction("CPX", NESCPU::cpx, AddressingMode.ZERO_PAGE, 3u),
            /*e5*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ZERO_PAGE, 3u),
            /*e6*/    NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ZERO_PAGE, 5u),
            /*e7*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            /*e8*/    NESAssembledInstruction("INX", NESCPU::inx, AddressingMode.IMPLIED, 2u),
            /*e9*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.IMMEDIATE, 2u),
            /*ea*/    NESAssembledInstruction("NOP", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*eb*/    NESAssembledInstruction("???", NESCPU::sbc, AddressingMode.IMPLIED, 2u),
            /*ec*/    NESAssembledInstruction("CPX", NESCPU::cpx, AddressingMode.ABSOLUTE, 4u),
            /*ed*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ABSOLUTE, 4u),
            /*ee*/    NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ABSOLUTE, 6u),
            /*ef*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*f0*/    NESAssembledInstruction("BEQ", NESCPU::beq, AddressingMode.RELATIVE, 2u),
            /*f1*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.INDIRECT_Y, 5u, DummyRead.ON_CARRY),
            /*f2*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            /*f3*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u, DummyRead.ALWAYS),
            /*f4*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ZERO_PAGE_X, 4u),
            /*f5*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ZERO_PAGE_X, 4u),
            /*f6*/    NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ZERO_PAGE_X, 6u),
            /*f7*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            /*f8*/    NESAssembledInstruction("SED", NESCPU::sed, AddressingMode.IMPLIED, 2u),
            /*f9*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ABSOLUTE_Y, 4u, DummyRead.ON_CARRY),
            /*fa*/    NESAssembledInstruction("NOP", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            /*fb*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS),
            /*fc*/    NESAssembledInstruction("???", NESCPU::nop, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*fd*/    NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ABSOLUTE_X, 4u, DummyRead.ON_CARRY),
            /*fe*/    NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ABSOLUTE_X, 7u, DummyRead.ALWAYS),
            /*ff*/    NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u, DummyRead.ALWAYS)
        )


    }
}