/*
 *  MIT License
 *
 *  Copyright (c) 2021 Gael Rial Costas
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

package io.github.gaeqs.nes4jams.cpu.instruction

import io.github.gaeqs.nes4jams.cpu.NESCPU
import kotlin.reflect.KFunction
import io.github.gaeqs.nes4jams.cpu.instruction.NESAddressingMode as AddressingMode

data class NESAssembledInstruction(
    val mnemonic: String,
    val operation: KFunction<Boolean>,
    val addressingMode: AddressingMode,
    val cycles: UByte
) {
    companion object {

        val INSTRUCTIONS = arrayOf(
            NESAssembledInstruction("BRK", NESCPU::brk, AddressingMode.IMMEDIATE, 7u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ZERO_PAGE, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("PHP", NESCPU::php, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("BPL", NESCPU::bpl, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ZERO_PAGE_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("CLC", NESCPU::clc, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("ORA", NESCPU::ora, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("ASL", NESCPU::asl, AddressingMode.ABSOLUTE_X, 7u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("JSR", NESCPU::jsr, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("BIT", NESCPU::bit, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ZERO_PAGE, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("PLP", NESCPU::plp, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("BIT", NESCPU::bit, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("BMI", NESCPU::bmi, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ZERO_PAGE_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("SEC", NESCPU::sec, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("AND", NESCPU::and, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("ROL", NESCPU::rol, AddressingMode.ABSOLUTE_X, 7u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("RTI", NESCPU::rti, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ZERO_PAGE, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("PHA", NESCPU::pha, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("JMP", NESCPU::jmp, AddressingMode.ABSOLUTE, 3u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("BVC", NESCPU::bvc, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ZERO_PAGE_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("CLI", NESCPU::cli, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("EOR", NESCPU::eor, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("LSR", NESCPU::lsr, AddressingMode.ABSOLUTE_X, 7u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("RTS", NESCPU::rts, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ZERO_PAGE, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("PLA", NESCPU::pla, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("JMP", NESCPU::jmp, AddressingMode.INDIRECT, 5u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("BVS", NESCPU::bvs, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ZERO_PAGE_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("SEI", NESCPU::sei, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("ADC", NESCPU::adc, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("ROR", NESCPU::ror, AddressingMode.ABSOLUTE_X, 7u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("STY", NESCPU::sty, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("STX", NESCPU::stx, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("DEY", NESCPU::dey, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("TXA", NESCPU::txa, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("STY", NESCPU::sty, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("STX", NESCPU::stx, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("BCC", NESCPU::bcc, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.INDIRECT_Y, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("STY", NESCPU::sty, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("STX", NESCPU::stx, AddressingMode.ZERO_PAGE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("TYA", NESCPU::tya, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ABSOLUTE_Y, 5u),
            NESAssembledInstruction("TXS", NESCPU::txs, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("STA", NESCPU::sta, AddressingMode.ABSOLUTE_X, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 3u),
            NESAssembledInstruction("TAY", NESCPU::tay, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("TAX", NESCPU::tax, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("BCS", NESCPU::bcs, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ZERO_PAGE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("CLV", NESCPU::clv, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("TSX", NESCPU::tsx, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("LDY", NESCPU::ldy, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("LDA", NESCPU::lda, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("LDX", NESCPU::ldx, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("CPY", NESCPU::cpy, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("CPY", NESCPU::cpy, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ZERO_PAGE, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("INY", NESCPU::iny, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("DEX", NESCPU::dex, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("CPY", NESCPU::cpy, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("BNE", NESCPU::bne, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ZERO_PAGE_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("CLD", NESCPU::cld, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("NOP", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("CMP", NESCPU::cmp, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("DEC", NESCPU::dec, AddressingMode.ABSOLUTE_X, 7u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("CPX", NESCPU::cpx, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.INDIRECT_X, 6u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("CPX", NESCPU::cpx, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ZERO_PAGE, 3u),
            NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ZERO_PAGE, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 5u),
            NESAssembledInstruction("INX", NESCPU::inx, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.IMMEDIATE, 2u),
            NESAssembledInstruction("NOP", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::sbc, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("CPX", NESCPU::cpx, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ABSOLUTE, 4u),
            NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ABSOLUTE, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("BEQ", NESCPU::beq, AddressingMode.RELATIVE, 2u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.INDIRECT_Y, 5u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 8u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ZERO_PAGE_X, 4u),
            NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ZERO_PAGE_X, 6u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 6u),
            NESAssembledInstruction("SED", NESCPU::sed, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ABSOLUTE_Y, 4u),
            NESAssembledInstruction("NOP", NESCPU::nop, AddressingMode.IMPLIED, 2u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u),
            NESAssembledInstruction("???", NESCPU::nop, AddressingMode.IMPLIED, 4u),
            NESAssembledInstruction("SBC", NESCPU::sbc, AddressingMode.ABSOLUTE_X, 4u),
            NESAssembledInstruction("INC", NESCPU::inc, AddressingMode.ABSOLUTE_X, 7u),
            NESAssembledInstruction("???", NESCPU::ill, AddressingMode.IMPLIED, 7u)
        )


    }
}